In [49]:
import pandas as pd
import numpy as np
import os

In [50]:
reliability_scores = pd.read_csv('../../../experiments/reliability_scores.csv')
reliability_scores.std()

path_id    5.916080
intra      0.097293
inter      0.034097
overall    0.058804
dtype: float64

In [51]:
reliability_scores.mean()

path_id    10.500000
intra       0.664794
inter       0.738546
overall     0.701670
dtype: float64

In [52]:
summary_df = pd.read_csv('../../../experiments/acc_alpha_summary.csv').round(4)
summary_df

,experiment,model_strat,panel_strat,acc_consensus,acc_virtual_5,acc_virtual_20,alpha_consensus,alpha_virtual_5,alpha_virtual_20,avg_acc,avg_alpha,mean_entropy,mean_frequency_entropy
0,consensus_best_2_4_10_13_20,consensus,best,0.7538,0.7692,0.7692,0.7326,0.7483,0.7573,0.7641,0.7461,0.4680,0.1069
1,consensus_cluster_2_13_14_15_16,consensus,cluster,0.7538,0.7615,0.7692,0.7326,0.7504,0.7573,0.7615,0.7468,0.4680,0.1069
2,consensus_random_1_5_9_14_20,consensus,random,0.7538,0.7462,0.7692,0.7326,0.7307,0.7573,0.7564,0.7402,0.4680,0.1069
3,virtual20_best_2_4_10_13_20,virtual20,best,0.7846,0.8077,0.8077,0.7739,0.7770,0.7855,0.8000,0.7788,0.6098,0.4057
4,virtual20_cluster_2_13_14_15_16,virtual20,cluster,0.7846,0.8000,0.8077,0.7739,0.7787,0.7855,0.7974,0.7794,0.6098,0.4057
5,virtual20_random_1_5_9_14_20,virtual20,random,0.7846,0.7692,0.8077,0.7739,0.7390,0.7855,0.7872,0.7661,0.6098,0.4057
6,virtual5_best_2_4_10_13_20,virtual5,best,0.7692,0.7769,0.7923,0.7679,0.7614,0.7787,0.7795,0.7693,0.5520,0.2774
7,virtual5_cluster_2_13_14_15_16,virtual5,cluster,0.7846,0.7846,0.7923,0.7670,0.7619,0.7688,0.7872,0.7659,0.5796,0.3867
8,virtual5_random_1_5_9_14_20,virtual5,random,0.7615,0.7615,0.7846,0.7410,0.7137,0.7509,0.7692,0.7352,0.6558,0.3504

In [62]:
bins = pd.read_csv('../../../experiments/acc_bins.csv')
bins["length"].sum()

130

In [66]:
top = pd.read_csv('../../../experiments/final_eval/virtual_5_cluster_2_13_14_15_16.csv')
top

,block_id,pred_score_0,pred_score_1,pred_score_2,softmax_scores_0,softmax_scores_1,softmax_scores_2,pred_class,cons_label,panel_label_selected,panel_label_all,entropy,frequency_classes_prediction_0,frequency_classes_prediction_1,frequency_classes_prediction_2,normalized_frequency_classes_prediction_0,normalized_frequency_classes_prediction_1,normalized_frequency_classes_prediction_2,pred_class_majority,frequency_entropy
0,RL-1001-I,-2.297161,0.638504,-0.093384,0.022046,0.574689,0.403266,1,1,1.0,1.0,0.768661,0,16,9,0.00,0.64,0.36,1,6.534182e-01
1,RL-1001-II,0.883313,-0.351626,-2.336052,0.896715,0.097260,0.006024,0,0,0.0,0.0,0.355205,21,4,0,0.84,0.16,0.00,0,4.396699e-01
2,RL-1001-III,0.911965,-0.457933,-2.253851,0.873874,0.117132,0.008994,0,0,0.0,0.0,0.411372,23,2,0,0.92,0.08,0.00,0,2.787694e-01
3,RL-1002-II,-1.616612,0.581154,-0.705557,0.096598,0.790786,0.112616,1,1,1.0,1.0,0.657316,0,25,0,0.00,1.00,0.00,1,-1.000000e-10
4,RL-1003-I,-2.103676,-0.189970,0.628967,0.027013,0.126988,0.845999,2,2,2.0,2.0,0.501097,1,0,24,0.04,0.00,0.96,2,1.679441e-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,RL-1097-II,0.825111,-0.437896,-1.748326,0.896398,0.093697,0.009905,0,0,0.0,0.0,0.365595,24,1,0,0.96,0.04,0.00,0,1.679441e-01
126,RL-1098-I,-1.813192,0.822329,-0.948495,0.086887,0.764749,0.148364,1,1,1.0,1.0,0.700481,0,22,3,0.00,0.88,0.12,1,3.669250e-01
127,RL-1098-II,-1.262088,-0.598385,0.328258,0.180409,0.249950,0.569641,2,2,1.0,2.0,0.976075,7,3,15,0.28,0.12,0.60,2,9.173574e-01
128,RL-1099-I,-2.254360,0.447391,0.409799,0.038675,0.681680,0.279645,1,1,1.0,1.0,0.743342,0,21,4,0.00,0.84,0.16,1,4.396699e-01
129,RL-1100-II,1.095635,-0.265142,-2.414478,0.934221,0.061185,0.004594,0,1,0.0,0.0,0.259237,24,1,0,0.96,0.04,0.00,0,1.679441e-01