In [399]:
import pandas as pd
import numpy as np
import os

In [400]:
reliability_scores = pd.read_csv('../../../experiments/reliability_scores.csv')
reliability_scores.std()

path_id    5.916080
intra      0.097293
inter      0.034097
overall    0.058804
dtype: float64

In [401]:
reliability_scores.mean()

path_id    10.500000
intra       0.664794
inter       0.738546
overall     0.701670
dtype: float64

In [414]:
summary_df = pd.read_csv('../../../experiments/acc_alpha_summary.csv')
f1_cols = summary_df.columns[summary_df.columns.str.contains('f1')].tolist()
summary_df[f1_cols].round(3)

,f1_consensus,f1_consensus_dev,f1_virtual_5,f1_virtual_5_dev,f1_virtual_20,f1_virtual_20_dev,avg_f1
0,0.727,0.087,0.744,0.089,0.740,0.090,0.737
1,0.722,0.087,0.719,0.088,0.736,0.089,0.726
2,0.726,0.086,0.717,0.084,0.739,0.087,0.727
3,0.773,0.082,0.802,0.078,0.796,0.082,0.790
4,0.772,0.080,0.782,0.084,0.796,0.080,0.783
5,0.769,0.080,0.760,0.086,0.792,0.082,0.774
6,0.758,0.079,0.763,0.085,0.783,0.080,0.768
7,0.775,0.080,0.758,0.086,0.773,0.085,0.769
8,0.750,0.084,0.767,0.081,0.774,0.084,0.764

In [403]:
summary_df

,experiment,model_strat,panel_strat,acc_consensus,acc_consensus_dev,acc_virtual_5,acc_virtual_5_dev,acc_virtual_20,acc_virtual_20_dev,f1_consensus,...,alpha_consensus,alpha_consensus_dev,alpha_virtual_5,alpha_virtual_5_dev,alpha_virtual_20,alpha_virtual_20_dev,avg_acc,avg_alpha,mean_entropy,mean_frequency_entropy
0,consensus_best_2_4_10_13_20,consensus,best,0.7527,0.0731,0.7685,0.0692,0.7686,0.0692,0.7232,...,0.7283,0.0971,0.7446,0.0901,0.7537,0.0888,0.7633,0.7422,0.4680,0.1069
1,consensus_cluster_2_13_14_15_16,consensus,cluster,0.7537,0.0731,0.7616,0.0731,0.7691,0.0731,0.7244,...,0.7277,0.0984,0.7456,0.0876,0.7524,0.0889,0.7614,0.7419,0.4680,0.1069
2,consensus_random_1_5_9_14_20,consensus,random,0.7549,0.0731,0.7473,0.0769,0.7701,0.0731,0.7254,...,0.7321,0.0968,0.7290,0.0868,0.7560,0.0910,0.7574,0.7390,0.4680,0.1069
3,virtual20_best_2_4_10_13_20,virtual20,best,0.7842,0.0692,0.8071,0.0654,0.8070,0.0654,0.7717,...,0.7701,0.0907,0.7734,0.0943,0.7817,0.0898,0.7994,0.7751,0.6098,0.4057
4,virtual20_cluster_2_13_14_15_16,virtual20,cluster,0.7847,0.0693,0.7999,0.0692,0.8079,0.0692,0.7726,...,0.7713,0.0883,0.7762,0.0907,0.7833,0.0892,0.7975,0.7769,0.6098,0.4057
5,virtual20_random_1_5_9_14_20,virtual20,random,0.7859,0.0693,0.7707,0.0692,0.8089,0.0692,0.7744,...,0.7710,0.0879,0.7369,0.0966,0.7832,0.0903,0.7885,0.7637,0.6098,0.4057
6,virtual5_best_2_4_10_13_20,virtual5,best,0.7692,0.0692,0.7772,0.0692,0.7927,0.0654,0.7578,...,0.7650,0.0867,0.7584,0.0919,0.7761,0.0914,0.7797,0.7665,0.5520,0.2774
7,virtual5_cluster_2_13_14_15_16,virtual5,cluster,0.7870,0.0692,0.7876,0.0692,0.7954,0.0692,0.7789,...,0.7652,0.0906,0.7611,0.0922,0.7683,0.0870,0.7900,0.7649,0.5796,0.3867
8,virtual5_random_1_5_9_14_20,virtual5,random,0.7609,0.0731,0.7617,0.0731,0.7842,0.0731,0.7495,...,0.7386,0.0928,0.7111,0.0986,0.7483,0.0929,0.7689,0.7327,0.6558,0.3504

In [404]:
summary_df["mean_entropy"]

0    0.4680
1    0.4680
2    0.4680
3    0.6098
4    0.6098
5    0.6098
6    0.5520
7    0.5796
8    0.6558
Name: mean_entropy, dtype: float64

In [405]:
summary_df["f1_consensus"]

0    0.7232
1    0.7244
2    0.7254
3    0.7717
4    0.7726
5    0.7744
6    0.7578
7    0.7789
8    0.7495
Name: f1_consensus, dtype: float64

In [406]:
bins = pd.read_csv('../../../experiments/acc_bins.csv')
bins["length"].sum()

390

In [407]:
top = pd.read_csv('../../../experiments/final_eval/virtual_5_cluster_2_13_14_15_16.csv')
top

,block_id,pred_score_0,pred_score_1,pred_score_2,softmax_scores_0,softmax_scores_1,softmax_scores_2,pred_class,cons_label,panel_label_selected,panel_label_all,entropy,frequency_classes_prediction_0,frequency_classes_prediction_1,frequency_classes_prediction_2,normalized_frequency_classes_prediction_0,normalized_frequency_classes_prediction_1,normalized_frequency_classes_prediction_2,pred_class_majority,frequency_entropy
0,RL-1001-I,-2.297161,0.638504,-0.093384,0.022046,0.574689,0.403266,1,1,1.0,1.0,0.768661,0,16,9,0.00,0.64,0.36,1,6.534182e-01
1,RL-1001-II,0.883313,-0.351626,-2.336052,0.896715,0.097260,0.006024,0,0,0.0,0.0,0.355205,21,4,0,0.84,0.16,0.00,0,4.396699e-01
2,RL-1001-III,0.911965,-0.457933,-2.253851,0.873874,0.117132,0.008994,0,0,0.0,0.0,0.411372,23,2,0,0.92,0.08,0.00,0,2.787694e-01
3,RL-1002-II,-1.616612,0.581154,-0.705557,0.096598,0.790786,0.112616,1,1,1.0,1.0,0.657316,0,25,0,0.00,1.00,0.00,1,-1.000000e-10
4,RL-1003-I,-2.103676,-0.189970,0.628967,0.027013,0.126988,0.845999,2,2,2.0,2.0,0.501097,1,0,24,0.04,0.00,0.96,2,1.679441e-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,RL-1097-II,0.825111,-0.437896,-1.748326,0.896398,0.093697,0.009905,0,0,0.0,0.0,0.365595,24,1,0,0.96,0.04,0.00,0,1.679441e-01
126,RL-1098-I,-1.813192,0.822329,-0.948495,0.086887,0.764749,0.148364,1,1,1.0,1.0,0.700481,0,22,3,0.00,0.88,0.12,1,3.669250e-01
127,RL-1098-II,-1.262088,-0.598385,0.328258,0.180409,0.249950,0.569641,2,2,1.0,2.0,0.976075,7,3,15,0.28,0.12,0.60,2,9.173574e-01
128,RL-1099-I,-2.254360,0.447391,0.409799,0.038675,0.681680,0.279645,1,1,1.0,1.0,0.743342,0,21,4,0.00,0.84,0.16,1,4.396699e-01
129,RL-1100-II,1.095635,-0.265142,-2.414478,0.934221,0.061185,0.004594,0,1,0.0,0.0,0.259237,24,1,0,0.96,0.04,0.00,0,1.679441e-01

In [408]:
intra_f1 = pd.read_csv("../../../experiments/intra_f1.csv")

In [409]:
reliability_intra = pd.read_csv("../../../experiments/reliability_scores.csv")["intra"]
reliability_intra

0     0.657480
1     0.824960
2     0.710341
3     0.738225
4     0.696920
5     0.551544
6     0.592970
7     0.497519
8     0.696195
9     0.774385
10    0.670603
11    0.723177
12    0.821839
13    0.539469
14    0.688525
15    0.586628
16    0.603757
17    0.497474
18    0.707675
19    0.716195
Name: intra, dtype: float64

In [410]:
round(intra_f1, 4)

    path_id  intra_f1
0         1    0.6701
1         2    0.7561
2         3    0.7150
3         4    0.6931
4         5    0.7016
5         6    0.5753
6         7    0.6520
7         8    0.4901
8         9    0.6743
9        10    0.7737
10       11    0.6628
11       12    0.7515
12       13    0.7507
13       14    0.5611
14       15    0.5792
15       16    0.5934
16       17    0.6441
17       18    0.5661
18       19    0.6917
19       20    0.6434

In [411]:
intra_f1.describe().round(4)

       path_id  intra_f1
count  20.0000   20.0000
mean   10.5000    0.6573
std     5.9161    0.0768
min     1.0000    0.4901
25%     5.7500    0.5899
50%    10.5000    0.6665
75%    15.2500    0.7050
max    20.0000    0.7737

In [412]:
abs(reliability_intra - intra_f1["intra_f1"]).describe().round(4)

count    20.0000
mean      0.0346
std       0.0307
min       0.0007
25%       0.0077
50%       0.0228
75%       0.0615
max       0.1093
dtype: float64

In [413]:
abs(reliability_intra - intra_f1["intra_f1"])

0     0.012635
1     0.068841
2     0.004630
3     0.045161
4     0.004693
5     0.023742
6     0.059069
7     0.007400
8     0.021884
9     0.000705
10    0.007760
11    0.028342
12    0.071120
13    0.021588
14    0.109294
15    0.006770
16    0.040325
17    0.068622
18    0.015932
19    0.072838
dtype: float64