In [54]:
import pandas as pd
import krippendorff as kd
import numpy as np
from sklearn.metrics import accuracy_score
import os

In [55]:
results = []
for experiment in sorted(os.listdir("../../../experiments/final_eval/")):
    df = pd.read_csv(f"../../../experiments/final_eval/{experiment}")
    acc_cons = accuracy_score(df["cons_label"], df["pred_class"])
    acc_virtual20 = accuracy_score(df["panel_label_all"], df["pred_class"])
    alpha_cons = kd.alpha(df[["cons_label", "pred_class"]].T.values, level_of_measurement="ordinal", value_domain=[0, 1.0, 2.0])
    alpha_virtual5 = kd.alpha(df[["panel_label_selected", "pred_class"]].T.values, level_of_measurement="ordinal", value_domain=[0, 1.0, 2.0])
    #note: dropna only here to keep others consistebt
    df = df.dropna(subset=["panel_label_selected"])
    acc_virtual5 = accuracy_score(df["panel_label_selected"], df["pred_class"])
    alpha_virtual20 = kd.alpha(df[["panel_label_all", "pred_class"]].T.values, level_of_measurement="ordinal", value_domain=[0, 1.0, 2.0])

    results.append(
        {
            "experiment": experiment.replace(".csv", ""),
            "acc_consensus": acc_cons,
            "acc_virtual_5": acc_virtual5,
            "acc_virtual_20": acc_virtual20,
            "alpha_consensus": alpha_cons,
            "alpha_virtual_5": alpha_virtual5,
            "alpha_virtual_20": alpha_virtual20
        }
    )

results_df = pd.DataFrame(results)

In [56]:
results_df.sort_values(by=["acc_consensus", "alpha_virtual_20"], ascending=False)

,experiment,acc_consensus,acc_virtual_5,acc_virtual_20,alpha_consensus,alpha_virtual_5,alpha_virtual_20
3,virtual_20_best_2_4_10_12_13,0.777778,0.796992,0.798611,0.765487,0.771741,0.784393
4,virtual_20_cluster_2_15_16_17_20,0.777778,0.807407,0.798611,0.765487,0.773614,0.781091
5,virtual_20_random_1_2_6_9_10,0.777778,0.807143,0.798611,0.765487,0.767629,0.780381
6,virtual_5_best_2_4_10_12_13,0.763889,0.781955,0.784722,0.751304,0.757917,0.771004
7,virtual_5_cluster_2_15_16_17_20,0.763889,0.777778,0.784722,0.751304,0.737917,0.766475
8,virtual_5_random_1_2_6_9_10,0.763889,0.785714,0.784722,0.751304,0.766129,0.765891
0,consensus_best_2_4_10_12_13,0.756944,0.774436,0.770833,0.740334,0.764891,0.777907
1,consensus_cluster_2_15_16_17_20,0.756944,0.755556,0.770833,0.740334,0.709093,0.770239
2,consensus_random_1_2_6_9_10,0.756944,0.771429,0.770833,0.740334,0.766886,0.766754

In [57]:
df

,block_id,pred_score_0,pred_score_1,pred_score_2,softmax_scores_0,softmax_scores_1,softmax_scores_2,pred_class,cons_label,panel_label_selected,panel_label_all
0,RL-1001-I,-3.192419,1.110273,-0.019506,0.025588,0.617905,0.356506,1,1,1.0,1.0
1,RL-1001-II,0.943599,0.089094,-3.998614,0.920705,0.077014,0.002282,0,0,0.0,0.0
2,RL-1001-III,0.353446,0.282021,-3.493481,0.886645,0.109767,0.003588,0,0,0.0,0.0
3,RL-1002-II,-1.795022,0.879431,-1.665949,0.127341,0.817264,0.055396,1,1,1.0,1.0
4,RL-1003-I,-3.087234,-0.347132,2.293329,0.011372,0.096638,0.891990,2,2,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...
139,RL-1098-I,-2.706976,1.280859,-1.129675,0.031888,0.836668,0.131445,1,1,1.0,1.0
140,RL-1098-II,-1.948578,0.088238,-0.182474,0.108643,0.445942,0.445415,1,2,2.0,2.0
141,RL-1099-I,-2.178737,0.615095,-0.441709,0.039673,0.658313,0.302014,1,1,1.0,1.0
142,RL-1100-I,-0.654775,0.081812,-1.754913,0.338589,0.500645,0.160766,1,1,2.0,1.0
143,RL-1100-II,1.331748,0.230711,-4.450609,0.926486,0.071801,0.001713,0,1,1.0,0.0